---
version: "3.8"

services:
  nginx-http-flv-module:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: nginx
    ports:
      - 5239:80 # http
      - 1935:1935 # rtmp
    volumes:
      - /opt/appdata/nginx:/www # http-assets
      - /opt/appdata/config/nginx.conf:/etc/nginx/nginx.conf # nginx.conf
    restart: always

  cn-nginx-http-flv-module:
    build:
      context: ./
      dockerfile: ./cn_Dockerfile
    container_name: nginx
    ports:
      - 5239:80 # http
      - 1935:1935 # rtmp
    volumes:
      - /opt/appdata/nginx:/www # http-assets
      - /opt/appdata/config/nginx.conf:/etc/nginx/nginx.conf # nginx.conf
    restart: always
